theme = dark:"Muxy",light:"Modus Operandi Tinted"
font-size = 16
font-family = "MonoLisa Nerd Font"
font-family-bold = "MonoLisa Nerd Font Bold"
font-family-italic = "MonoLisa Nerd Font Italic"
font-family-bold-italic = "MonoLisa Nerd Font Bold Italic"
font-style-bold = true
